import Head from 'next/head'

// styles
import styles from '../styles/Home.module.scss'

// components
import ProductCard from '../components/ProductCard'

// hooks
import { useAppDispatch, useAppSelector } from '../app/hooks'

// reducer actions
import { massDeleteProduct } from '../features/productSlice'
import Link from 'next/link'

export default function Home() {
  const products = useAppSelector(state => state.products.products)
  const dispatch = useAppDispatch()

  const handleMassDeleteButton = () => {
    dispatch(massDeleteProduct())
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Scandiweb Junior Developer test assignment!</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>

        <div className={styles.header}>
          <h1>Product List</h1>
          <div className='header-btn'>
            <Link href='/addproduct'><button>ADD</button></Link>
            <button id='delete-product-btn' onClick={handleMassDeleteButton}>MASS DELETE</button>
          </div>
        </div>

        <div className={styles.grid}>
          {!products.length ? <div>There is no product, please add a new product</div> : products.map(product => (
            <ProductCard key={product.sku} product={product} />
          ))}
        </div>

      </main>

      <footer className={styles.footer}>
        <p>Scandiweb Test assigment <a target='_blank' rel='noreferrer' href='https://alexisxz.github.io/my-site/'>Alexis Matos da Silva</a></p>
      </footer>
    </div>
  )
}
